theme: jekyll-theme-minimal
title: Alex's homepage
description: Bookmark this to keep an eye on my project updates!
social-network-links:
  email: "mx@sigtstp.com"
  github: sigtstp
exclude:
  - CNAME
  - README.md